produit/urls.py
from django.conf.urls import url
from . import views
app_name = 'boutique'
urlpatterns=[




    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),


    url(r'^create_boutique/$', views.create_boutique, name='create_boutique'),
    url(r'^$', views.index, name='index'),
    url(r'^produits/(?P<filter_by>[a-zA_Z]+)/$', views.produits, name='produits'),
    url(r'^(?P<boutique_id>[0-9]+)/create_produit/$', views.create_produit, name='create_produit'),
    url(r'^(?P<boutique_id>[0-9]+)/delete_produit/(?P<produit_id>[0-9]+)/$', views.delete_produit, name='delete_produit'),
    url(r'^(?P<boutique_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<produit_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^(?P<produit_id>[0-9]+)/smile/$', views.smile, name='smile'),
    url(r'^(?P<boutique_id>[0-9]+)/delete_boutique/$', views.delete_boutique, name='delete_boutique'),
    url(r'^vosproduit/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail_produit'),
    url(r'^activer/(?P<produit_id>[0-9]+)/$', views.Activer, name='activer'),
    url(r'^desactiv/(?P<produit_id>[0-9]+)/$', views.DesActiver, name='desactiver'),
    url(r'^produits/$', views.post_list, name='post_list'),
    url(r'^categorie/$', views.Categorie, name='Categorie'),

]

projet3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^boutique/', include('produit.urls')),
    url(r'^', include('produit.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produit/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
import datetime

class Boutique(models.Model):
    name = models.CharField(max_length=250)
    user = models.ForeignKey(User, default=1)
    logo = models.FileField(max_length=250)

    def __str__(self):
        return self.name

now = datetime.datetime.now()

def group_based_upload_to(instance, filename):
    return "image//media/ali/{}/{}".format(instance.boutique.name, filename)
def group_based_upload_to_seconder(instance, filename):
    return "image//media/ali/secondaire/{}/{}".format(instance.boutique.name, filename)
class Image(models.Model):
    image1 = models.ImageField(upload_to=group_based_upload_to_seconder, default=None)
    image2 = models.ImageField(upload_to=group_based_upload_to_seconder, default=None)
    image3 = models.ImageField(upload_to=group_based_upload_to_seconder, default=None)

class Produit(models.Model):
    etat_choix = (('active', 'active'),('desactive','desactive'),)
    user = models.ForeignKey(User, default=1)
    choix_categorie = (('bijoux', 'bijoux'), ('maison et ameublement', 'maison et ameublement'), ('vetements', 'vetements'),('art et collections', 'art et collections'),('accessoires', 'accessoires'),('sacs et bagages', 'sacs et bagages'),('mariage', 'mariage'),)
    prix = models.CharField(max_length=250)
    title = models.CharField(max_length=250)
    type = models.CharField(max_length=250, default=None)
    etat = models.CharField(max_length=250, choices=etat_choix, default="desactive" )
    descreption = models.CharField(max_length=250)
    boutique = models.ForeignKey(Boutique, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to=group_based_upload_to)
    image1 = models.ImageField(upload_to=group_based_upload_to_seconder, default=None)
    image2 = models.ImageField(upload_to=group_based_upload_to_seconder, default=None)
    image3 = models.ImageField(upload_to=group_based_upload_to_seconder, default=None)
    categorie = models.CharField(max_length=250, choices=choix_categorie, default="bijoux")
    is_favorite = models.BooleanField(default=False)
    is_smile = models.BooleanField(default=False)





    def __str__(self):
        return self.title+' - ' +self.prix

    def __str__(self):  # __unicode__ on Python 2
        return self.title

    class Meta:
        ordering = ('title',)

produit/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Boutique, Produit


class BoutiqueForm(forms.ModelForm):

    class Meta:
        model = Boutique
        fields = ['name', 'logo']


class ProduitForm(forms.ModelForm):

    class Meta:
        model = Produit
        fields = ['prix', 'title', 'descreption', 'type', 'etat', 'categorie','logo', 'image1' , 'image2', 'image3']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

produit/views.py
from django.views import generic
from .models import Boutique, Produit
from .forms import BoutiqueForm, UserForm, ProduitForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def group_based_upload_to(instance, filename):
    return "image/boutique/{}/{}".format(instance.boutique.name, filename)

def detail(request, boutique_id):
    if not request.user.is_authenticated():
        return render(request, 'produit/login.html')
    else:
        user = request.user
        boutique = get_object_or_404(Boutique, pk=boutique_id)
        return render(request, 'produit/detail.html', {'boutique': boutique, 'user': user})

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'produit/login.html')
    else:
        boutiques = Boutique.objects.filter(user=request.user)
        produit_results = Produit.objects.all()
        query = request.GET.get("q")
        if query:
            boutiques = boutiques.filter(
                Q(name__icontains=query)


            ).distinct()
            produit_results = produit_results.filter(
                Q(title__icontains=query),
                Q(categorie__icontains=query)

            ).distinct()
            return render(request, 'produit/index.html', {
                'boutiques': boutiques,
                'produits': produit_results,
            })
        else:
            return render(request, 'produit/index.html', {'boutiques': boutiques})


def create_boutique(request):
    if not request.user.is_authenticated():
        return render(request, 'produit/login.html')
    else:
        form = BoutiqueForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            boutique = form.save(commit=False)
            boutique.user = request.user
            boutique.logo = request.FILES['logo']
            file_type = boutique.logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'boutique': boutique,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'produit/create_boutique.html', context)
            boutique.save()
            return render(request, 'produit/detail.html', {'boutique': boutique})
        context = {
            "form": form,
        }
        return render(request, 'produit/create_boutique.html', context)

def Activer(request, produit_id):
    produit = Produit.objects.get(pk=produit_id)
    produit.etat = "active"
    produit.save()
    return JsonResponse({'success':True})

def DesActiver(request, produit_id):
    produit = Produit.objects.get(pk=produit_id)
    produit.etat = "desactive"
    produit.save()
    return JsonResponse({'failure':True})


def delete_boutique(request, boutique_id):
    boutique = Boutique.objects.get(pk=boutique_id)
    boutique.delete()
    boutiques = Boutique.objects.filter(user=request.user)
    return render(request, 'produit/index.html', {'boutique': boutiques})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'produit/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Boutique.objects.filter(user=request.user)
                return render(request, 'produit/index.html', {'albums': albums})
            else:
                return render(request, 'produit/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'produit/login.html', {'error_message': 'Invalid login'})
    return render(request, 'produit/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                boutiques = Boutique.objects.filter(user=request.user)
                return render(request, 'produit/index.html', {'boutique': boutiques})
    context = {
        "form": form,
    }
    return render(request, 'produit/register.html', context)


def produits(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'produit/login.html')
    else:
        try:
            produit_ids = []
            for boutique in Boutique.objects.filter(user=request.user):
                for produit in boutique.produit_set.all():
                    produit_ids.append(produit.pk)
            users_produits = Produit.objects.filter(pk__in=produit_ids)
            if filter_by == 'favorites':
                users_produits = users_produits.filter(is_favorite=True)
        except Boutique.DoesNotExist:
            users_produits = []
        return render(request, 'produit/produits.html', {
            'produit_list': users_produits,
            'filter_by': filter_by,

        })




def create_produit(request, boutique_id):
    form = ProduitForm(request.POST or None, request.FILES or None)
    boutique = get_object_or_404(Boutique, pk=boutique_id)
    if form.is_valid():
        boutiques_produits = boutique.produit_set.all()
        for s in boutiques_produits:
            if s.title == form.cleaned_data.get("title"):
                context = {
                    'boutique': boutique,
                    'form': form,
                    'error_message': 'You already added that produit',
                }
                return render(request, 'produit/create_produit.html', context)
        produit = form.save(commit=False)
        produit.boutique = boutique

        produit.save()
        return render(request, 'produit/detail.html', {'boutique': boutique})
    context = {
        'boutique': boutique,
        'form': form,
    }
    return render(request, 'produit/create_produit.html', context)

def delete_produit(request, boutique_id, produit_id):
    boutique = get_object_or_404(Boutique, pk=boutique_id)
    produit = Produit.objects.get(pk=produit_id)
    produit.delete()
    return render(request, 'produit/detail.html', {'boutique': boutique})




class DetailView(generic.DetailView):
    model = Produit
    template_name = 'produit/detail-produit.html'

def post_list(request):
    list_produit = Produit.objects.all()
    paginator = Paginator(list_produit,4)
    page = request.GET.get('page')
    try:
        produits= paginator.page(page)
    except PageNotAnInteger:
        produits = paginator.page(1)
    except EmptyPage:
        produits = paginator.page(paginator.num_pages)
    return render(request, 'produit/produits.html',{'page':page, 'produits':produits})


def Categorie(request):
    produit_results = Produit.objects.all()
    categorie = Produit.choix_categorie
    if categorie:
        produit_results = produit_results.filter(
        Q(title__icontains=categorie)
         ).distinct()
    return render(request, 'produit/produits.html', {
        'produit1': produit_results,
    })

def favorite(request, produit_id):
    variable = get_object_or_404(Produit, pk=produit_id)
    try:
        if variable.is_favorite:
            variable.is_favorite = False
        else:
            variable.is_favorite = True
            variable.save()
    except (KeyError, Produit.DoesNotExist):
        return JsonResponse({'success':False})
    else:
        return JsonResponse({'success':True})



def smile(request, produit_id):
    produit = get_object_or_404(Produit, pk=produit_id)
    try:
        if produit.is_smile:
            produit.is_smile = False
        else:
            produit.is_smile = True
            produit.save()
    except (KeyError, Produit.DoesNotExist):
        return JsonResponse({'success':False})
    else:
        return JsonResponse({'success':True})

produit/templates/produit/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Boutique Maker{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'shopping.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'produit/style.css' %}"/>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="{% static 'produit/js/main.js' %}"></script>
    <script src="{% static 'produit/js/index.js' %}"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'boutique:index' %}">Boutique Maker</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'boutique:index' %}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp; Boutiques</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'boutique:post_list' %}"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>&nbsp; Produits</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'boutique:index' %} ">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Name    Categorie" >
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'boutique:create_boutique' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Boutique
                    </a>
                </li>
                <li>
                    <a href="{% url 'boutique:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

produit/templates/produit/boutique_form.html
{% extends 'produit/base.html' %}


{% block body %}
<div class="container-fluid">

	<div class="row">

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'produit/form-template.html' %}
						<div class="form-group"></div>
							<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>

							</div>
					</form>

				</div>

			</div>

		</div>

	</div>
</div>
{% endblock %}

produit/templates/produit/create_produit.html
{% extends 'produit/base.html' %}
{% block title %}Add a New produit{% endblock %}
{% block boutiques_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left boutique Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'boutique:detail' boutique.id %}">
                            {% if boutique.logo %}
                                <img src="{{ boutique.logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ boutique.name }}</h1>
                </div>
            </div>
        </div>

        <!-- Right produit Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'boutique:detail' boutique.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'boutique:create_produit' boutique.id %}">Add New produit</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New produit</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="boutique" value="{{ boutique }}">
                        {% include 'produit/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

produit/templates/produit/descover.html
{% extends 'produit/base.html' %}
{% block title %}All produuits{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'boutique:produits' 'all' %}">View All</a></li>

            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">

                        <tbody>

                            {% for produit in produit_list %}


                                 <div class="col-sm-8 col-lg-3">
                                    <div class="thumbnail">
                                            <a href="{% url 'boutique:detail_produit' produit.id %}">
                                                <img src="{{ produit.logo.url }}"  style="width:500px;height:200px;" class="img-responsive">
                                            </a>
                                            <div class="caption">
                                                <h2>{{ produit.name }}</h2>


                                                <!-- View Details -->
                                                <a href="{% url 'boutique:detail_produit' produit.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>


                                                <!-- Delete Album -->


                                                <!-- Favorite Album -->


                                            </div>
                                        </div>
                                    </div>

                                <!--  tableux  ----------------->


                            {% endfor %}
                        </tbody>



                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

produit/templates/produit/detail.html
{% extends 'produit/base.html' %}
{% block title %}{{ boutique }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid produits-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'boutique:detail' boutique.id %}">
                        {% if boutique.logo %}
                            <img src="{{ boutique.logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ boutique.name }} </h1>

                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'boutique:detail' boutique.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'boutique:create_produit' boutique.id %}">Ajouter New Produit</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All products</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>product name</th>


                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for produit in boutique.produit_set.all %}
                            <tr>
                            <td> <li><a href="{% url 'boutique:detail_produit' produit.id %}"> {{produit.title}}</a></li></td>

                                <td>
                                    <form action="{% url 'boutique:delete_produit' boutique.id produit.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ produit.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

produit/templates/produit/index.html
{% extends 'produit/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if boutiques %}
            {% for boutique in boutiques %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'boutique:detail' boutique.id %}">
                            <img src="{{ boutique.logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ boutique.name }}</h2>


                            <!-- View Details -->
                            <a href="{% url 'boutique:detail' boutique.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>


                            <!-- Delete Album -->

                            <form action="{% url 'boutique:delete_boutique' boutique.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="boutique_id" value="{{ boutique.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                             </form>
                            <!-- Favorite Album -->


                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'boutique:create_boutique' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Boutique
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->


{% if produits %}

            <div class="col-sm-12">
                <h3>Produits</h3>
            </div>
            <div class="col-sm-12">





                                {% for produit in produits %}

  <div class="col-md-6"><img src="{{ produit.logo.url }}" style="width:600px;height:600px;"></div>

       <div class="col-xs-6 .col-md-1"><img src="{{ produit.image1.url }}" style="width:200px;height:200px;"> </div>
        <div class="col-xs-6 .col-md-1"><img src="{{ produit.image2.url }}" style="width:200px;height:200px;"> </div>
        <div class="col-xs-6 .col-md-1"><img src="{{ produit.image3.url }}" style="width:200px;height:200px;"> </div>

<div>
    <ul>
        <li> <h3>product name : {{ produit.title }}</h3></li>
        <h3>produit prix : {{ produit.prix }}</h3>
        <h3> product description : {{ produit.descreption }}</h3>
        <h3>produit etat : {{ produit.etat }}</h3>

    </ul>

</div>

	{% if error_message %}
	 	<p>{{error_message}}</p>
	 {% endif%}
    </div>




                                {% endfor %}



                </div>

    {% endif %}

{% endblock %}

produit/templates/produit/login.html
{% extends 'produit/base_visitor.html' %}
{% block body %}
    <div class="login-box">
        <div class="lb-header">
            <a href="{% url 'boutique:login_user' %}" class="active" id="login-box-link">Login</a>
            <a href="{% url 'boutique:register' %}" id="signup-box-link">Sign Up</a>
        </div>
    <div class="social-login">
      <a href="#">
        <i class="fa fa-facebook fa-lg"></i>
        Login in with facebook
      </a>
      <a href="#">
        <i class="fa fa-google-plus fa-lg"></i>
        log in with Google
      </a>
    </div>
   <form class="email-login"  action="{% url 'boutique:login_user'%}" method="post" enctype="multipart/form-data">
       {% csrf_token %}
       <div class="u-form-group">
           <div class="col-sm-10">
           <input  maxlength="30"  name="username" type="text" placeholder="username">
               <br>
               <br>
       </div>
       </div>


       <div class="u-form-group">

        <div class="col-sm-10">

            <input  maxlength="30" placeholder="password" name="password" type="password">
            <br>
               <br>
        </div>
       </div>
        <div class="u-form-group">

            <div class="col-sm-offset-1 col-sm-8">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

    </form>


  </div>


{% endblock %}

produit/templates/produit/produits.html
{% extends 'produit/base.html' %}

{% block title %}Tous les produuits{% endblock %}
{% block songs_active %}active{% endblock %}
<div class="col-sm-offset-1 ">
{% block pagination %}

{% block body %}
    <div class="container-fluid Produits-container">
    {% for produit in produits %}





                                 <div class="col-sm-2 col-lg-4">
                                    <div class="thumbnail">

                                                <img src="{{ produit.logo.url }}"  style="width:500px;height:200px;" class="img-responsive">
                                    <div>{{ produit.title }}</div>


                                            <div class="caption">



<!--<input type="checkbox" checked data-toggle="toggle" data-on="Ready" data-off="Not Ready" data-onstyle="success" data-offstyle="danger"> -->
 {% if produit.etat == "active" %}
<a href="{% url 'boutique:desactiver' produit.id %}" > <input type="button" value="Activer"> </a>
     {% else %}
<a href="{% url 'boutique:activer' produit.id %}" > <input type="button" value="Desactiver"> </a>
     <a href="{% url 'boutique:detail_produit' produit.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
{% endif %}
          <a href="{% url 'boutique:favorite' produit.id %}" class="btn-favorite"><span class="glyphicon glyphicon-heart {% if produit.is_favorite %}active{%else%}not{% endif %}"></span></a>
           <a href="{% url 'boutique:smile' produit.id %}" class="btn-favorite"><span class="fa fa-smile-o {% if produit.is_smile %}active{% endif %}"></span></a>


                                                <!-- Delete Album -->


                                                <!-- Favorite Album -->


                                            </div>
                                        </div>
                                    </div>

    {% endfor %}
{% include "produit/pagination.html" with page=produits %}
    </div>
  </div>
{% endblock %}
{% endblock %}